config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "tasks", to: "tasks#index"
  get 'tasks/new', to: "tasks#new"
  post 'tasks', to: "tasks#create"
  get 'tasks/:id', to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit"
  patch "tasks/:id", to: "tasks#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = task.new(params[:task])
    @task.save
    redirect_to task_path(@task)
  end

  private
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def edit
    @task = task.find(params[:id])
  end

  def update
    @task = task.find(params[:id])
    @task.update(params[:task])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h1>hellow</h1>

app/views/tasks/index.html.erb
<h1>Hello</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= task.title %></li>
  <% end %>
</ul>
<%= link_to "add a task", tasks_new_path %>

app/views/tasks/new.html.erb
<%= form_with model: @restaurant do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :detail %>
  <%= f.text_field :detail %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>